name: 'Thank You Action'
description: "Say 'Thank You' to new pull request"
author: 'Sandip Rijal'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
